# For conda build
package:
  name: rmg
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
    - mingwpy # [win]
  host:
    - boost ==1.56.0
    - cython >=0.25.2
    - jinja2
    - lpsolve55
    - numpy
    - openbabel >=2.4.1
    - pydas >=1.0.2
    - pydqed >=1.0.1
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - scipy
    - scoop
    - setuptools
  run:
    - argparse # [py26]
    - cairo
    - cairocffi
    - cantera >=2.3.0a3
    - coolprop
    - coverage
    - cython >=0.25.2
    - ffmpeg
    - gprof2dot
    - graphviz
    - guppy
    - jinja2
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - mock
    - mopac
    - mpmath
    - nose
    - {{ pin_compatible('numpy') }}
    - openbabel >=2.4.1
    - psutil
    - pydas >=1.0.2
    - pydot ==1.2.2
    - pydqed >=1.0.1
    - pymongo
    - pyparsing
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - rmgdatabase >=2.2.0
    - scipy
    - scoop
    - symmetry
    - xlwt

test:
  source_files:
    - 'examples/rmg/superminimal'
  imports:
    - rmgpy
  commands:
    - rmg.py examples/rmg/superminimal/input.py # [unix]
    - python %SCRIPTS%\rmg.py examples\rmg\superminimal\input.py # [win]

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
