# For conda build
package:
  name: rmg
  version: "0" # set by build.sh, which gets from rmgpy/__init__.py

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - argparse # [py26]
    - boost ==1.56.0
    - cairo # [unix]
    - cairocffi # [unix]
    - coverage
    - cython >=0.25.2
    - gcc # [unix]
    - gcc ==4.8.2 # [linux32]
    - gprof2dot
    - jinja2
    - libgcc # [unix]
    - libgfortran ==1.0 # [linux] You may need to comment this out for mac osx
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - nose
    - numpy
    - openbabel
    - psutil
    - pydas >=1.0.2
    - pydot ==1.2.2
    - pydqed >=1.0.1
    - pyparsing
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - scipy
    - scoop
    - setuptools
    - xlwt

  run:
    - argparse # [py26]
    - cairo # [unix]
    - cairocffi # [unix]
    - cantera >=2.2
    - coolprop
    - coverage
    - cython ==0.21
    - ffmpeg
    - gprof2dot
    - graphviz
    - guppy
    - jinja2
    - libgcc # [unix]
    - libgfortran ==1.0 # [linux] You may need to comment this out for mac osx
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - mock
    - mopac
    - nose
    - numpy
    - openbabel
    - psutil
    - pydas >=1.0.2
    - pydot ==1.2.2
    - pydqed >=1.0.1
    - pyparsing
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - rmgdatabase >=2.1.0
    - scipy
    - scoop
    - symmetry
    - xlwt

test:
  source_files:
    - '*'
  requires:
    - nose
  imports:
    - rmgpy
  commands:
    - cp $PREFIX/lib/python2.7/site-packages/rmgpy/rmgrc $SRC_DIR [unix]
    - make -C $SRC_DIR test [unix]
    - cp %PREFIX%\Lib\site-packages\rmgpy\rmgrc %SRC_DIR% [win]
    - mingw32-make -C %SRC_DIR% test [win]

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
