#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0.
"""
autoGenerated=True
entry(
    index = 0,
    label = "oxygen + acetyl <=> acetylperoxy",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.65e+06,'m^3/(mol*s)'), n=0, Ea=(0,'kcal/mol'), T0=(1,'K')),
)

