#!/usr/bin/env python
# encoding: utf-8

name = "kinetics"
shortDesc = ""
longDesc = """
Calculated using Arkane v3.1.0 using LevelOfTheory(method='ccsd(t)f12',basis='ccpvqzf12').
"""
autoGenerated=True
