# For conda build
package:
  name: rmg
  version: 3.2.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }} # [unix]
  host:
    - cython >=0.25.2
    - lpsolve55
    - numpy
    - openbabel >=3
    - pydas >=1.0.2
    - pydqed >=1.0.1
    - pyrdl
    - python
    - quantities
    - rdkit >=2018
    - scipy
    - setuptools
  run:
    - cairo
    - cairocffi
    - cantera >=2.3.0
    - cclib >=1.6.3
    - chemprop
    - coolprop
    - coverage
    - cython >=0.25.2
    - ffmpeg
    - gprof2dot
    - graphviz
    - h5py
    - jinja2
    - jupyter
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - mopac
    - mpmath
    - muq2
    - networkx
    - nose
    - numdifftools
    - {{ pin_compatible('numpy') }}
    - openbabel >=3
    - pandas
    - psutil
    - pydas >=1.0.2
    - pydot
    - pydqed >=1.0.1
    - pymongo
    - pyparsing
    - pyrdl
    - python
    - pyyaml
    - pyzmq
    - quantities
    - rdkit >=2018
    - rmgdatabase >=3.2.0
    - scikit-learn
    - scipy
    - symmetry
    - xlrd
    - xlwt
test:
  source_files:
    - 'examples/rmg/superminimal'
    - 'examples/arkane/networks/n-butanol'
  imports:
    - rmgpy
    - arkane
  commands:
    - rmg.py examples/rmg/superminimal/input.py # [unix]
    - Arkane.py examples/arkane/networks/n-butanol/input.py # [unix]
    - python %SCRIPTS%\rmg.py examples\rmg\superminimal\input.py # [win]
    - python %SCRIPTS\Arkane.py examples\arkane\networks\n-butanol\input.py # [win]

about:
  home: https://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
