# meta.yaml
#
# welcome to meta.yaml, poor soul that you are. this file specifies the 'recipe' for compiling
# RMG-Py into binaries which can then be uploaded for access via the conda package manager
# to use this file, you can follow the procedure shown in .github/workflows/conda_build.yml
#
package:
  name: rmg
  version: 3.3.0

source:
  path: ../

build:
  number: 0
  script: |
    python utilities.py check-pydas  # write the rmgpy/solver/settings.pxi file
    python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg >=7
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz >=12
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::graphviz 
    - conda-forge::pyopenssl >20
    - conda-forge::coolprop
    - conda-forge::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,<1.9
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.9
    - conda-forge::setuptools <80
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2,<3.1
    - conda-forge::scikit-learn
    - conda-forge::scipy >=1.9
    - conda-forge::numpy >=1.10.0,<2
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::pytest-check
    - conda-forge::pyutilib
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities !=0.16.0,!=0.16.1
    - conda-forge::ringdecomposerlib-python
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::symmetry
    - rmg::rmgdatabase =3.3.0
    - blas=*=openblas
  run:
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg >=7
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz >=12
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::graphviz 
    - conda-forge::pyopenssl >20
    - conda-forge::coolprop
    - conda-forge::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,<1.9
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.9
    - conda-forge::setuptools <80
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2,<3.1
    - conda-forge::scikit-learn
    - conda-forge::scipy >=1.9
    - conda-forge::numpy >=1.10.0,<2
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::pytest-check
    - conda-forge::pyutilib
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities !=0.16.0,!=0.16.1
    - conda-forge::ringdecomposerlib-python
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::symmetry
    - rmg::rmgdatabase =3.3.0
    - blas=*=openblas
test:
  requires:
    - conda-forge::cairo
    - conda-forge::cairocffi
    - conda-forge::ffmpeg >=7
    - conda-forge::xlrd
    - conda-forge::xlwt
    - conda-forge::h5py
    - conda-forge::graphviz >=12
    - conda-forge::markupsafe
    - conda-forge::psutil
    - conda-forge::ncurses
    - conda-forge::suitesparse
    - conda-forge::graphviz 
    - conda-forge::pyopenssl >20
    - conda-forge::coolprop
    - conda-forge::cantera =2.6
    - conda-forge::mopac
    - conda-forge::cclib >=1.6.3,<1.9
    - conda-forge::openbabel >=3
    - conda-forge::rdkit >=2022.09.1
    - conda-forge::python >=3.9
    - conda-forge::setuptools <80
    - conda-forge::coverage
    - conda-forge::cython >=0.25.2,<3.1
    - conda-forge::scikit-learn
    - conda-forge::scipy >=1.9
    - conda-forge::numpy >=1.10.0,<2
    - conda-forge::pydot
    - conda-forge::jinja2
    - conda-forge::jupyter
    - conda-forge::pymongo
    - conda-forge::pyparsing
    - conda-forge::pyyaml
    - conda-forge::networkx
    - conda-forge::pytest
    - conda-forge::pytest-cov
    - conda-forge::pytest-check
    - conda-forge::pyutilib
    - conda-forge::matplotlib >=1.5
    - conda-forge::mpmath
    - conda-forge::pandas
    - conda-forge::gprof2dot
    - conda-forge::numdifftools
    - conda-forge::quantities !=0.16.0,!=0.16.1
    - conda-forge::ringdecomposerlib-python
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::symmetry
    - rmg::rmgdatabase =3.3.0
    - blas=*=openblas
  source_files:
    - 'examples/rmg/superminimal'
    - 'examples/arkane/networks/n-butanol_msc'
  imports:
    - rmgpy
    - arkane
  commands:
    - rmg.py examples/rmg/superminimal/input.py
    - Arkane.py examples/arkane/networks/n-butanol_msc/input.py

about:
  home: https://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
