# For conda build
package:
  name: rmg
  version: 3.2.0

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cairo
    - cairocffi
    - ffmpeg
    - xlrd
    - xlwt
    - h5py
    - graphviz
    - markupsafe
    - psutil
    - ncurses
    - suitesparse
    - coolprop
    - cantera=2.6
    - mopac
    - cclib >=1.6.3,!=1.8.0
    - openbabel >= 3
    - rdkit >=2022.09.1
    - julia=1.9.1
    - pyjulia >=0.6
    - python >=3.7
    - coverage
    - cython >=0.25.2
    - scikit-learn
    - scipy <1.11
    - numpy >=1.10.0
    - pydot
    - jinja2
    - jupyter
    - pymongo
    - pyparsing
    - pyyaml
    - networkx
    - pytest
    - pytest-cov
    - pip
    - pip:
      - pytest-check
    - matplotlib >=1.5
    - mpmath
    - pandas
    - gprof2dot
    - numdifftools
    - quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::pyrms
    - rmg::symmetry
    - rmg::diffeqpy
    - nomkl
  run:
    - cairo
    - cairocffi
    - ffmpeg
    - xlrd
    - xlwt
    - h5py
    - graphviz
    - markupsafe
    - psutil
    - ncurses
    - suitesparse
    - coolprop
    - cantera=2.6
    - mopac
    - cclib >=1.6.3,!=1.8.0
    - openbabel >= 3
    - rdkit >=2022.09.1
    - julia=1.9.1
    - pyjulia >=0.6
    - python >=3.7
    - coverage
    - cython >=0.25.2
    - scikit-learn
    - scipy <1.11
    - numpy >=1.10.0
    - pydot
    - jinja2
    - jupyter
    - pymongo
    - pyparsing
    - pyyaml
    - networkx
    - pytest
    - pytest-cov
    - pip
    - pip:
      - pytest-check
    - matplotlib >=1.5
    - mpmath
    - pandas
    - gprof2dot
    - numdifftools
    - quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::pyrms
    - rmg::symmetry
    - rmg::diffeqpy
    - nomkl
test:
  requires:
    - cairo
    - cairocffi
    - ffmpeg
    - xlrd
    - xlwt
    - h5py
    - graphviz
    - markupsafe
    - psutil
    - ncurses
    - suitesparse
    - coolprop
    - cantera=2.6
    - mopac
    - cclib >=1.6.3,!=1.8.0
    - openbabel >= 3
    - rdkit >=2022.09.1
    - julia=1.9.1
    - pyjulia >=0.6
    - python >=3.7
    - coverage
    - cython >=0.25.2
    - scikit-learn
    - scipy <1.11
    - numpy >=1.10.0
    - pydot
    - jinja2
    - jupyter
    - pymongo
    - pyparsing
    - pyyaml
    - networkx
    - pytest
    - pytest-cov
    - pip
    - pip:
      - pytest-check
    - matplotlib >=1.5
    - mpmath
    - pandas
    - gprof2dot
    - numdifftools
    - quantities
    - rmg::lpsolve55
    - rmg::muq2
    - rmg::pydas >=1.0.3
    - rmg::pydqed >=1.0.3
    - rmg::pyrdl
    - rmg::pyrms
    - rmg::symmetry
    - rmg::diffeqpy
    - nomkl
  source_files:
    - 'examples/rmg/superminimal'
    - 'examples/arkane/networks/n-butanol'
  imports:
    - rmgpy
    - arkane
  commands:
    - rmg.py examples/rmg/superminimal/input.py
    - Arkane.py examples/arkane/networks/n-butanol/input.py

about:
  home: https://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."