name: Conda Build

on:
  pull_request:
  push:
    branches:
      - stable
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-solver: libmamba
          auto-activate-base: true
          activate-environment: ""
      - name: Install Build Tools
        run: conda install anaconda-client conda-build=3.28.4
      - name: Configure Auto-Upload
        if: github.ref == 'refs/heads/stable'
        run: |
          conda config --set anaconda_upload yes
      - name: Build Binary
        env: 
          CONDA_TOKEN: "need_to_add_this_secret"  # ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda config --add channels rmg
          conda config --add channels cantera
          conda config --add channels conda-forge
          conda build --token $CONDA_TOKEN --user rmg .conda
